language: php

services:
- mysql

php:
- 7.2

before_script:
- cp .env.travis .env
- composer install --no-interaction
- php artisan key:generate
- php artisan jwt:secret --force
- php artisan migrate --seed

script:
- vendor/bin/phpunit